<template>
    <view class="padding-sm">
        <scroll-view style="height: 30vh;width:100%" :scroll-y="true" class="padding bg-black">
            开始差量编译...
            DONE Build complete. Watching for changes...
            开始差量编译...
            DONE Build complete. Watching for changes...
            开始差量编译...
            DONE Build complete. Watching for changes...
            开始差量编译...
            DONE Build complete. Watching for changes...
        </scroll-view>
    </view>
</template>

<script setup lang="ts">

</script>

<style scoped>
</style>